# This is a basic workflow to help you get started with Actions

name: Mirror

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          # SSH private key for ssh connection to the target repository
          ssh_private_key: ${{ secrets.GITLAB_PRIVATE_KEY }}
          # Target url
          target_repo_url: git@gitlab.com:weary/gocord.git
          # Username for ssh connection
          ssh_username: git
